# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check_Item_Logs',
            fields=[
                ('check_item_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('confirmation', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('NA', 'Not Applicable')], max_length=45)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Check_Session_Logs',
            fields=[
                ('check_session_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_date', models.DateTimeField()),
                ('check_remarks', models.TextField()),
                ('is_session_submitted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Checklists',
            fields=[
                ('checklist_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_registered', models.DateTimeField()),
                ('checklist_name', models.CharField(max_length=45)),
                ('checklist_desc', models.TextField()),
                ('last_edit', models.DateTimeField()),
                ('priority_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Classifications',
            fields=[
                ('classification_name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('classification_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('emp_id', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('building', models.CharField(max_length=45)),
                ('floor', models.CharField(max_length=45)),
                ('area', models.CharField(max_length=45)),
                ('location_hash', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Roles',
            fields=[
                ('role_name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('emp_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=45)),
                ('middle_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('role_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srac.User_Roles')),
            ],
        ),
        migrations.AddField(
            model_name='checklists',
            name='classification_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srac.Classifications'),
        ),
        migrations.AddField(
            model_name='checklists',
            name='edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_by', to='srac.Users'),
        ),
        migrations.AddField(
            model_name='checklists',
            name='location_hash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srac.Locations'),
        ),
        migrations.AddField(
            model_name='checklists',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_by', to='srac.Users'),
        ),
        migrations.AddField(
            model_name='check_session_logs',
            name='checker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srac.Users'),
        ),
        migrations.AddField(
            model_name='check_item_logs',
            name='check_session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srac.Check_Session_Logs'),
        ),
        migrations.AddField(
            model_name='check_item_logs',
            name='checklist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srac.Checklists'),
        ),
    ]
