# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srac', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Check_Item_Logs',
            new_name='Check_Item_Log',
        ),
        migrations.RenameModel(
            old_name='Check_Session_Logs',
            new_name='Check_Session_Log',
        ),
        migrations.RenameModel(
            old_name='Checklists',
            new_name='Checklist',
        ),
        migrations.RenameModel(
            old_name='Classifications',
            new_name='Classification',
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='User_Roles',
            new_name='User_Role',
        ),
    ]
